run:
  skip-dirs:
    - internal/kafka/internal/api/public
    - internal/kafka/internal/api/private
    - internal/kafka/internal/api/admin/private
    - internal/connector/internal/api/public
    - internal/connector/internal/api/private
    - internal/connector/internal/api/admin/private
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  timeout: 10m
linters:
  enable:
    - bodyclose
    - scopelint
    - forbidigo
linters-settings:
  forbidigo:
    forbid:
      # gomega (https://onsi.github.io/gomega/) library's RegisterTestingT method is now deprecated and NewWithT() should be used instead.
      # When having table-driven tests it should be instantiated in each subtest.
      # See https://pkg.go.dev/github.com/onsi/gomega#NewWithT for an example
      - 'RegisterTestingT(# RegisterTestingT is deprecated. Use https://pkg.go.dev/github.com/onsi/gomega#NewWithT instead)?'
